"""Auto-generated from QS World University Rankings 2026 (top 500).
Single source of truth for the university dropdown, QS-rank lookup, and
school-name normalization on import. Do not edit by hand — regenerate.
"""

# (rank, official_name, country, alias)
QS_TOP500 = [
    (1, 'Massachusetts Institute of Technology', 'United States', 'MIT'),
    (2, 'Imperial College London', 'United Kingdom', ''),
    (3, 'Stanford University', 'United States', ''),
    (4, 'University of Oxford', 'United Kingdom', ''),
    (5, 'Harvard University', 'United States', ''),
    (6, 'University of Cambridge', 'United Kingdom', ''),
    (7, 'ETH Zurich', 'Switzerland', ''),
    (8, 'National University of Singapore', 'Singapore', 'NUS'),
    (9, 'UCL', 'United Kingdom', ''),
    (10, 'California Institute of Technology', 'United States', 'Caltech'),
    (11, 'The University of Hong Kong', 'Hong Kong', ''),
    (12, 'Nanyang Technological University, Singapore', 'Singapore', ''),
    (13, 'University of Chicago', 'United States', ''),
    (14, 'Peking University', 'China', ''),
    (15, 'University of Pennsylvania', 'United States', ''),
    (16, 'Cornell University', 'United States', ''),
    (17, 'Tsinghua University', 'China', ''),
    (17, 'University of California, Berkeley', 'United States', 'UCB'),
    (19, 'The University of Melbourne', 'Australia', ''),
    (20, 'The University of New South Wales', 'Australia', ''),
    (21, 'Yale University', 'United States', ''),
    (22, 'École Polytechnique Fédérale de Lausanne', 'Switzerland', ''),
    (22, 'Technical University of Munich', 'Germany', ''),
    (24, 'Johns Hopkins University', 'United States', ''),
    (25, 'Princeton University', 'United States', ''),
    (25, 'The University of Sydney', 'Australia', ''),
    (27, 'McGill University', 'Canada', ''),
    (28, 'PSL University', 'France', ''),
    (29, 'University of Toronto', 'Canada', ''),
    (30, 'Fudan University', 'China', ''),
    (31, "King's College London", 'United Kingdom', 'KCL'),
    (32, 'Australian National University', 'Australia', ''),
    (32, 'The Chinese University of Hong Kong', 'Hong Kong', ''),
    (34, 'University of Edinburgh', 'United Kingdom', ''),
    (35, 'The University of Manchester', 'United Kingdom', ''),
    (36, 'Monash University', 'Australia', ''),
    (36, 'The University of Tokyo', 'Japan', ''),
    (38, 'Columbia University', 'United States', ''),
    (38, 'Seoul National University', 'South Korea', ''),
    (40, 'University of British Columbia', 'Canada', ''),
    (41, 'Institut Polytechnique de Paris', 'France', ''),
    (42, 'Northwestern University', 'United States', ''),
    (42, 'The University of Queensland', 'Australia', ''),
    (44, 'The Hong Kong University of Science and Technology', 'Hong Kong', ''),
    (45, 'University of Michigan-Ann Arbor', 'United States', ''),
    (46, 'University of California, Los Angeles', 'United States', 'UCLA'),
    (47, 'Delft University of Technology', 'Netherlands', ''),
    (47, 'Shanghai Jiao Tong University', 'China', ''),
    (49, 'Zhejiang University', 'China', ''),
    (50, 'Yonsei University', 'South Korea', ''),
    (51, 'University of Bristol', 'United Kingdom', ''),
    (52, 'Carnegie Mellon University', 'United States', ''),
    (53, 'The University of Amsterdam', 'Netherlands', ''),
    (54, 'The Hong Kong Polytechnic University', 'Hong Kong', ''),
    (55, 'New York University', 'United States', 'NYU'),
    (56, 'London School of Economics and Political Science', 'United Kingdom', 'LSE'),
    (57, 'Kyoto University', 'Japan', ''),
    (58, 'Ludwig-Maximilians-Universität München', 'Germany', ''),
    (58, 'Universiti Malaya', 'Malaysia', 'UM'),
    (60, 'KU Leuven', 'Belgium', ''),
    (61, 'Korea University', 'South Korea', ''),
    (62, 'Duke University', 'United States', ''),
    (63, 'City University of Hong Kong', 'Hong Kong', ''),
    (63, 'National Taiwan University', 'Taiwan', 'NTU'),
    (65, 'The University of Auckland', 'New Zealand', ''),
    (66, 'University of California, San Diego', 'United States', 'UCSD'),
    (67, 'King Fahd University of Petroleum & Minerals', 'Saudi Arabia', ''),
    (68, 'University of Texas at Austin', 'United States', ''),
    (69, 'Brown University', 'United States', ''),
    (70, 'Université Paris-Saclay', 'France', ''),
    (70, 'University of Illinois at Urbana-Champaign', 'United States', ''),
    (72, 'Lund University', 'Sweden', ''),
    (72, 'Sorbonne University', 'France', ''),
    (74, 'The University of Warwick', 'United Kingdom', ''),
    (75, 'Trinity College Dublin, The University of Dublin', 'Ireland', ''),
    (76, 'University of Birmingham', 'United Kingdom', ''),
    (77, 'The University of Western Australia', 'Australia', ''),
    (78, 'KTH Royal Institute of Technology', 'Sweden', ''),
    (79, 'University of Glasgow', 'United Kingdom', ''),
    (80, 'Ruprecht-Karls-Universität Heidelberg', 'Germany', ''),
    (81, 'University of Washington', 'United States', ''),
    (82, 'Adelaide University', 'Australia', ''),
    (82, 'Pennsylvania State University', 'United States', ''),
    (84, 'Universidad de Buenos Aires', 'Argentina', ''),
    (85, 'Tokyo Institute of Technology', 'Japan', ''),
    (86, 'University of Leeds', 'United Kingdom', ''),
    (87, 'University of Southampton', 'United Kingdom', ''),
    (88, 'Boston University', 'United States', ''),
    (88, 'Freie Universität Berlin', 'Germany', ''),
    (88, 'Purdue University', 'United States', ''),
    (91, 'The University of Osaka', 'Japan', ''),
    (92, 'The University of Sheffield', 'United Kingdom', ''),
    (93, 'Uppsala University', 'Sweden', ''),
    (94, 'Durham University', 'United Kingdom', ''),
    (94, 'University of Alberta', 'Canada', ''),
    (96, 'University of Technology Sydney', 'Australia', ''),
    (97, 'The University of Nottingham', 'United Kingdom', ''),
    (98, 'Karlsruhe Institute of Technology', 'Germany', 'KIT'),
    (98, 'Politecnico di Milano', 'Italy', ''),
    (100, 'University of Zurich', 'Switzerland', 'UZH'),
    (101, 'University of Copenhagen', 'Denmark', ''),
    (102, 'Pohang University of Science And Technology', 'South Korea', 'POSTECH'),
    (103, 'Nanjing University', 'China', ''),
    (103, 'Utrecht University', 'Netherlands', ''),
    (105, 'Lomonosov Moscow State University', 'Russia', ''),
    (105, 'Rheinisch-Westfälische Technische Hochschule Aachen', 'Germany', ''),
    (107, 'Technical University of Denmark', 'Denmark', ''),
    (108, 'Universidade de São Paulo', 'Brazil', 'USP'),
    (109, 'Tohoku University', 'Japan', ''),
    (110, 'Queen Mary University of London', 'United Kingdom', 'QMUL'),
    (110, 'University of Wisconsin-Madison', 'United States', ''),
    (112, 'Qatar University', 'Qatar', ''),
    (113, 'University of St Andrews', 'United Kingdom', ''),
    (114, 'Aalto University', 'Finland', ''),
    (114, 'University of California, Davis', 'United States', ''),
    (116, 'Pontificia Universidad Católica de Chile', 'Chile', ''),
    (116, 'University of Helsinki', 'Finland', ''),
    (118, 'University College Dublin', 'Ireland', ''),
    (119, 'Leiden University', 'Netherlands', ''),
    (119, 'Rice University', 'United States', ''),
    (119, 'University of Oslo', 'Norway', ''),
    (119, 'University of Waterloo', 'Canada', ''),
    (123, 'Georgia Institute of Technology', 'United States', ''),
    (123, 'Indian Institute of Technology Delhi', 'India', 'IITD'),
    (125, 'RMIT University', 'Australia', ''),
    (126, 'Sungkyunkwan University', 'South Korea', ''),
    (126, 'Universiti Kebangsaan Malaysia', 'Malaysia', 'UKM'),
    (128, 'Sapienza University of Rome', 'Italy', ''),
    (129, 'Indian Institute of Technology Bombay', 'India', 'IITB'),
    (130, 'Humboldt-Universität zu Berlin', 'Germany', ''),
    (131, 'Aarhus University', 'Denmark', ''),
    (132, 'University of Bath', 'United Kingdom', ''),
    (132, 'University of Science and Technology of China', 'China', ''),
    (134, 'Universiti Putra Malaysia', 'Malaysia', 'UPM'),
    (134, 'Universiti Sains Malaysia', 'Malaysia', 'USM'),
    (136, 'Universidad Nacional Autónoma de México', 'Mexico', 'UNAM'),
    (137, 'Newcastle University', 'United Kingdom', ''),
    (138, 'Alma Mater Studiorum - University of Bologna', 'Italy', ''),
    (138, 'Macquarie University', 'Australia', ''),
    (140, 'Eindhoven University of Technology', 'Netherlands', ''),
    (140, 'Erasmus University Rotterdam', 'Netherlands', ''),
    (140, 'University of North Carolina, Chapel Hill', 'United States', ''),
    (143, 'King Saud University', 'Saudi Arabia', ''),
    (144, 'Texas A&M University', 'United States', ''),
    (145, 'Technische Universität Berlin', 'Germany', ''),
    (146, 'University of Southern California', 'United States', ''),
    (147, 'Stockholm University', 'Sweden', ''),
    (147, 'University of Groningen', 'Netherlands', ''),
    (147, 'University of Liverpool', 'United Kingdom', ''),
    (150, 'University of Cape Town', 'South Africa', ''),
    (151, 'Western University', 'Canada', ''),
    (152, 'University of Vienna', 'Austria', ''),
    (153, 'Universiti Teknologi Malaysia', 'Malaysia', 'UTM'),
    (153, 'Wageningen University & Research', 'Netherlands', ''),
    (155, 'University of Exeter', 'United Kingdom', ''),
    (155, 'University of Geneva', 'Switzerland', ''),
    (157, 'Lancaster University', 'United Kingdom', ''),
    (158, 'University of Basel', 'Switzerland', ''),
    (159, 'Hanyang University', 'South Korea', ''),
    (160, 'University of Barcelona', 'Spain', ''),
    (161, 'Michigan State University', 'United States', ''),
    (162, 'Ghent University', 'Belgium', ''),
    (163, 'King Abdul Aziz University', 'Saudi Arabia', 'KAU'),
    (164, 'Nagoya University', 'Japan', ''),
    (165, 'Chalmers University of Technology', 'Sweden', ''),
    (166, 'Al-Farabi Kazakh National University', 'Kazakhstan', ''),
    (167, 'Washington University in St. Louis', 'United States', ''),
    (168, 'University of Montreal', 'Canada', ''),
    (169, 'University of York', 'United Kingdom', ''),
    (170, 'Hokkaido University', 'Japan', ''),
    (170, 'Kyushu University', 'Japan', ''),
    (172, 'Universitat Autónoma de Barcelona', 'Spain', ''),
    (173, 'Arizona State University', 'United States', ''),
    (173, 'McMaster University', 'Canada', ''),
    (173, 'Universidad de Chile', 'Chile', ''),
    (176, 'National Tsing Hua University', 'Taiwan', ''),
    (177, 'Khalifa University of Science and Technology', 'United Arab Emirates', ''),
    (177, 'Tongji University', 'China', ''),
    (179, 'University of California, Santa Barbara', 'United States', 'UCSB'),
    (180, 'Indian Institute of Technology Madras', 'India', 'IITM'),
    (181, 'Cardiff University', 'United Kingdom', ''),
    (182, 'Emory University', 'United States', ''),
    (183, 'Curtin University', 'Australia', ''),
    (184, 'University of Bern', 'Switzerland', ''),
    (184, 'University of Wollongong', 'Australia', ''),
    (186, 'Wuhan University', 'China', ''),
    (187, 'Tecnológico de Monterrey', 'Mexico', 'ITESM'),
    (187, 'University Complutense Madrid', 'Spain', ''),
    (189, 'UNIVERSITAS INDONESIA', 'Indonesia', ''),
    (190, 'Ohio State University', 'United States', ''),
    (191, "Queen's University, Ontario", 'Canada', ''),
    (191, 'Université Catholique de Louvain', 'Belgium', 'UCL'),
    (193, 'Universität Hamburg', 'Germany', ''),
    (194, 'University of Reading', 'United Kingdom', ''),
    (194, 'Vrije Universiteit Amsterdam', 'Netherlands', ''),
    (196, 'Waseda University', 'Japan', ''),
    (197, 'University of Otago', 'New Zealand', ''),
    (197, 'Vienna University of Technology', 'Austria', ''),
    (199, 'National Yang Ming Chiao Tung University', 'Taiwan', ''),
    (199, "Queen's University Belfast", 'United Kingdom', ''),
    (201, 'Universität Freiburg', 'Germany', ''),
    (202, 'University of Gothenburg', 'Sweden', ''),
    (203, 'National Cheng Kung University', 'Taiwan', 'NCKU'),
    (203, 'University of Twente', 'Netherlands', ''),
    (205, 'Ecole Normale Supérieure de Lyon', 'France', ''),
    (206, 'Universidad Autónoma de Madrid', 'Spain', ''),
    (207, 'Deakin University', 'Australia', ''),
    (207, 'Rheinische Friedrich-Wilhelms-Universität Bonn', 'Germany', ''),
    (207, 'University of Maryland, College Park', 'United States', ''),
    (210, 'University of Minnesota', 'United States', 'System'),
    (211, 'University of Calgary', 'Canada', ''),
    (212, 'Universidad de Los Andes Colombia', 'Colombia', ''),
    (212, 'University of Florida', 'United States', ''),
    (212, 'University of Lausanne', 'Switzerland', ''),
    (215, 'Eberhard Karls Universität Tübingen', 'Germany', ''),
    (215, 'Indian Institute of Technology Kharagpur', 'India', 'IITKGP'),
    (215, 'Keio University', 'Japan', ''),
    (218, 'Technische Universität Dresden', 'Germany', ''),
    (219, 'Indian Institute of Science (IISc) Bangalore', 'India', ''),
    (219, 'University of Ottawa', 'Canada', ''),
    (221, 'Chulalongkorn University', 'Thailand', ''),
    (222, 'Indian Institute of Technology Kanpur', 'India', 'IITK'),
    (223, 'Tel Aviv University', 'Israel', ''),
    (224, 'Universitas Gadjah Mada', 'Indonesia', ''),
    (225, 'Loughborough University', 'United Kingdom', ''),
    (226, 'Queensland University of Technology', 'Australia', ''),
    (227, 'The University of Newcastle', 'Australia', ''),
    (227, 'Université Libre de Bruxelles', 'Belgium', 'ULB'),
    (229, 'United Arab Emirates University', 'United Arab Emirates', ''),
    (230, 'Massey University', 'New Zealand', ''),
    (230, 'University of Lisbon', 'Portugal', ''),
    (232, 'Universität Erlangen-Nürnberg', 'Germany', ''),
    (233, 'La Trobe University', 'Australia', ''),
    (233, 'Universidade Estadual de Campinas', 'Brazil', 'Unicamp'),
    (233, 'University of Padova', 'Italy', ''),
    (236, 'University of Rochester', 'United States', ''),
    (237, 'American University of Beirut', 'Lebanon', 'AUB'),
    (237, 'University of Porto', 'Portugal', ''),
    (239, 'Maastricht University', 'Netherlands', ''),
    (240, 'Hebrew University of Jerusalem', 'Israel', ''),
    (240, 'Victoria University of Wellington', 'New Zealand', ''),
    (242, 'Politecnico di Torino', 'Italy', ''),
    (243, 'Georg-August-Universität Göttingen', 'Germany', ''),
    (244, 'Hamad Bin Khalifa University', 'Qatar', ''),
    (244, 'Hong Kong Baptist University', 'Hong Kong', ''),
    (246, 'University College Cork', 'Ireland', ''),
    (247, 'Beijing Normal University', 'China', ''),
    (247, 'Dartmouth College', 'United States', ''),
    (247, 'University of Massachusetts, Amherst', 'United States', ''),
    (250, 'Vanderbilt University', 'United States', ''),
    (251, 'Universiti Teknologi Petronas', 'Malaysia', 'UTP'),
    (251, 'University of Strathclyde', 'United Kingdom', ''),
    (253, "Taylor's University", 'Malaysia', 'Malaysia'),
    (253, 'Technische Universität Darmstadt', 'Germany', ''),
    (255, 'Bandung Institute of Technology', 'Indonesia', 'ITB'),
    (256, 'Harbin Institute of Technology', 'China', ''),
    (257, 'Tianjin University', 'China', ''),
    (257, 'Université Paris 1 Panthéon-Sorbonne', 'France', ''),
    (259, 'Beijing Institute of Technology', 'China', ''),
    (259, 'Universidad Nacional de Colombia', 'Colombia', ''),
    (261, 'University of Canterbury', 'New Zealand', ''),
    (262, 'University of Aberdeen', 'United Kingdom', ''),
    (262, 'University of Navarra', 'Spain', ''),
    (262, 'University of Surrey', 'United Kingdom', ''),
    (265, 'Charles University', 'Czechia', ''),
    (265, 'Universitat Pompeu Fabra', 'Spain', ''),
    (267, 'Norwegian University of Science And Technology', 'Norway', ''),
    (268, 'Griffith University', 'Australia', ''),
    (269, 'Middle East Technical University', 'Turkey', ''),
    (269, 'UCSI University', 'Malaysia', ''),
    (271, 'University of Warsaw', 'Poland', ''),
    (272, 'American University of Sharjah', 'United Arab Emirates', 'AUS'),
    (272, 'North Carolina State University', 'United States', ''),
    (272, 'Universität zu Köln', 'Germany', ''),
    (275, 'University of Virginia', 'United States', ''),
    (276, 'Sun Yat-sen University', 'China', ''),
    (276, 'University of Milan', 'Italy', ''),
    (278, 'University of Sussex', 'United Kingdom', ''),
    (279, 'Radboud University Nijmegen', 'Netherlands', ''),
    (280, 'University of Antwerp', 'Belgium', ''),
    (281, 'University of Pittsburgh', 'United States', ''),
    (281, 'University of Waikato', 'New Zealand', ''),
    (283, 'Dalhousie University', 'Canada', ''),
    (284, 'University of Galway / Ollscoil na Gaillimhe', 'Ireland', ''),
    (285, 'Georgetown University', 'United States', ''),
    (285, 'University of Macau', 'Macau', ''),
    (287, 'Heriot-Watt University', 'United Kingdom', ''),
    (287, 'Universitas Airlangga', 'Indonesia', ''),
    (287, 'University of Arizona', 'United States', ''),
    (287, 'University of Bergen', 'Norway', ''),
    (291, 'University of The Witwatersrand', 'South Africa', ''),
    (292, 'Swansea University', 'United Kingdom', ''),
    (293, 'University of California, Irvine', 'United States', ''),
    (294, 'Case Western Reserve University', 'United States', ''),
    (294, 'Swinburne University of Technology', 'Australia', ''),
    (294, 'University of Notre Dame', 'United States', ''),
    (294, 'Vrije Universiteit Brussel', 'Belgium', 'VUB'),
    (298, 'Istanbul Technical University', 'Turkey', ''),
    (299, 'University of Colorado Boulder', 'United States', ''),
    (300, 'Université Paris Cité', 'France', ''),
    (301, 'Universidad Carlos III de Madrid', 'Spain', ''),
    (302, 'Stellenbosch University', 'South Africa', ''),
    (303, 'Jagiellonian University', 'Poland', ''),
    (303, 'University of Southern Denmark', 'Denmark', ''),
    (305, "Xi'an Jiaotong University", 'China', ''),
    (306, 'Aalborg University', 'Denmark', ''),
    (306, 'Indiana University Bloomington', 'United States', ''),
    (308, 'Simon Fraser University', 'Canada', ''),
    (308, 'University of Johannesburg', 'South Africa', ''),
    (310, 'City St George’s, University of London', 'United Kingdom', ''),
    (310, 'Linköping University', 'Sweden', ''),
    (310, 'Ulsan National Institute of Science and Technology', 'South Korea', ''),
    (310, 'Universität Stuttgart', 'Germany', ''),
    (314, 'University of Miami', 'United States', ''),
    (314, 'University of Tasmania', 'Australia', ''),
    (316, 'Goethe Universität Frankfurt am Main', 'Germany', ''),
    (317, 'L.N. Gumilyov Eurasian National University', 'Kazakhstan', ''),
    (317, 'Universidade Federal do Rio de Janeiro', 'Brazil', ''),
    (319, 'Huazhong University of Science and Technology', 'China', ''),
    (320, 'Bauman Moscow State Technical University', 'Russia', ''),
    (321, 'Université Grenoble Alpes', 'France', ''),
    (322, 'University of Tehran', 'Iran', ''),
    (323, 'Koc University', 'Turkey', ''),
    (324, 'Sichuan University', 'China', ''),
    (324, 'University of Jordan', 'Jordan', ''),
    (326, 'University of Leicester', 'United Kingdom', ''),
    (327, 'Universidade Nova de Lisboa', 'Portugal', ''),
    (328, 'Rutgers University – New Brunswick', 'United States', ''),
    (328, 'University of Delhi', 'India', ''),
    (328, 'University of Sharjah', 'United Arab Emirates', ''),
    (331, 'Kyung Hee University', 'South Korea', ''),
    (331, 'Satbayev University', 'Kazakhstan', ''),
    (333, 'York University', 'Canada', ''),
    (334, 'Indian Institute of Technology Guwahati', 'India', 'IITG'),
    (334, 'Sultan Qaboos University', 'Oman', ''),
    (334, 'Tufts University', 'United States', ''),
    (334, 'Universidad Politécnica de Madrid', 'Spain', ''),
    (334, 'University of Illinois Chicago', 'United States', 'UIC'),
    (339, 'Indian Institute of Technology Roorkee', 'India', 'IITR'),
    (339, 'Shandong University', 'China', ''),
    (341, 'Xiamen University', 'China', ''),
    (342, 'University of Oulu', 'Finland', ''),
    (343, 'Southern University of Science and Technology', 'China', 'SUSTech'),
    (343, 'University of Pisa', 'Italy', ''),
    (345, 'National Taiwan University of Science and Technology', 'Taiwan', 'Taiwan Tech'),
    (345, 'Pontificia Universidad Católica del Perú', 'Peru', 'PUCP'),
    (347, 'Cairo University', 'Egypt', ''),
    (347, 'Tilburg University', 'Netherlands', ''),
    (347, 'University of Coimbra', 'Portugal', ''),
    (350, 'Technion - Israel Institute of Technology', 'Israel', ''),
    (350, 'Universität Innsbruck', 'Austria', ''),
    (350, 'University of Münster', 'Germany', ''),
    (350, 'University of Tsukuba', 'Japan', ''),
    (354, 'Quaid-i-azam University', 'Pakistan', ''),
    (355, 'Nankai University', 'China', ''),
    (355, 'National Technical University of Athens', 'Greece', ''),
    (355, 'Università degli Studi di Roma - Tor Vergata', 'Italy', ''),
    (358, 'George Washington University', 'United States', ''),
    (358, 'Mahidol University', 'Thailand', ''),
    (358, 'University of Victoria', 'Canada', ''),
    (358, 'Virginia Polytechnic Institute', 'United States', ''),
    (362, 'University of Chinese Academy of Sciences', 'China', 'UCAS'),
    (362, 'University of Pretoria', 'South Africa', ''),
    (362, 'University of Tartu', 'Estonia', ''),
    (362, 'University of the Philippines', 'Philippines', ''),
    (366, 'University of Turku', 'Finland', ''),
    (367, 'RUDN University', 'Russia', ''),
    (367, 'Sciences Po Paris', 'France', ''),
    (367, 'Universiti Brunei Darussalam', 'Brunei', 'UBD'),
    (370, 'Daegu Gyeongbuk Institute of Science and Technology', 'South Korea', 'DGIST'),
    (371, 'Bogazici University', 'Turkey', ''),
    (371, 'National University of Sciences And Technology (NUST) Islamabad', 'Pakistan', ''),
    (371, 'Pontificia Universidad Javeriana', 'Colombia', ''),
    (374, 'Oxford Brookes University', 'United Kingdom', ''),
    (375, 'Saint Petersburg State University', 'Russia', ''),
    (375, 'Sharif University of Technology', 'Iran', ''),
    (377, 'South China University of Technology', 'China', ''),
    (378, 'University of Saskatchewan', 'Canada', ''),
    (379, 'University of Liege', 'Belgium', ''),
    (379, 'University of Naples - Federico II', 'Italy', ''),
    (381, 'The American University in Cairo', 'Egypt', ''),
    (381, 'University of East Anglia', 'United Kingdom', 'UEA'),
    (381, 'University of Luxembourg', 'Luxembourg', ''),
    (384, 'Northeastern University', 'United States', ''),
    (385, 'Brunel University of London', 'United Kingdom', ''),
    (385, 'Gwangju Institute of Science and Technology', 'South Korea', 'GIST'),
    (387, 'Flinders University', 'Australia', ''),
    (388, 'Beihang University', 'China', 'former BUAA'),
    (388, 'Birkbeck College, University of London', 'United Kingdom', ''),
    (390, 'National and Kapodistrian University of Athens', 'Greece', ''),
    (391, 'Abu Dhabi University', 'United Arab Emirates', ''),
    (392, 'Sejong University', 'South Korea', ''),
    (392, 'Southeast University, China', 'China', ''),
    (392, 'Universitat Politècnica de Catalunya', 'Spain', ''),
    (395, 'Aston University', 'United Kingdom', ''),
    (395, 'Ruhr-Universität Bochum', 'Germany', ''),
    (397, 'Lappeenranta-Lahti University of Technology LUT', 'Finland', ''),
    (397, 'University of Kent', 'United Kingdom', ''),
    (399, 'IPB University', 'Indonesia', ''),
    (400, 'Western Sydney University', 'Australia', ''),
    (401, 'Umeå University', 'Sweden', ''),
    (401, 'University of Granada', 'Spain', ''),
    (401, 'University of Limerick', 'Ireland', ''),
    (404, 'Sabanci University', 'Turkey', ''),
    (404, 'University of Florence', 'Italy', ''),
    (406, 'Institut National des Sciences Appliquées de Lyon', 'France', 'INSA'),
    (407, 'Lincoln University', 'New Zealand', ''),
    (408, 'University of Turin', 'Italy', ''),
    (409, 'Università\xa0 Cattolica del Sacro Cuore', 'Italy', ''),
    (410, 'Auckland University of Technology', 'New Zealand', ''),
    (410, 'Dublin City University', 'Ireland', ''),
    (410, 'Sunway University', 'Malaysia', ''),
    (410, 'University at Buffalo SUNY', 'United States', ''),
    (410, 'University of Southern Queensland', 'Australia', ''),
    (415, 'Bilkent University', 'Turkey', ''),
    (416, 'Czech Technical University In Prague', 'Czechia', ''),
    (416, 'Julius-Maximilians-Universität Würzburg', 'Germany', ''),
    (416, 'Universität Mannheim', 'Germany', ''),
    (419, 'University of Aveiro', 'Portugal', ''),
    (420, 'National Taipei University of Technology', 'Taiwan', ''),
    (420, 'Université de Strasbourg', 'France', ''),
    (422, 'Universitat Politecnica de Valencia', 'Spain', ''),
    (423, 'Murdoch University', 'Australia', ''),
    (423, 'Tampere University', 'Finland', ''),
    (423, 'Università\xa0 degli Studi di Pavia', 'Italy', ''),
    (423, 'Washington State University', 'United States', ''),
    (427, 'Graz University of Technology', 'Austria', ''),
    (428, 'Aix-Marseille University', 'France', ''),
    (428, 'University of Dundee', 'United Kingdom', ''),
    (430, 'Masaryk University', 'Czechia', ''),
    (430, 'Universitat de Valencia', 'Spain', ''),
    (430, 'Université de Montpellier', 'France', ''),
    (433, 'East China Normal University', 'China', ''),
    (433, 'Leibniz Universität Hannover', 'Germany', ''),
    (435, 'National Taiwan Normal University', 'Taiwan', ''),
    (436, 'Prince Mohammad Bin Fahd University', 'Saudi Arabia', ''),
    (436, 'Universitat Ramon Llull', 'Spain', ''),
    (438, 'IE University', 'Spain', ''),
    (439, 'National Sun Yat-sen University', 'Taiwan', ''),
    (440, 'Ajman University', 'United Arab Emirates', ''),
    (440, 'James Cook University', 'Australia', ''),
    (440, 'Macau University of Science and Technology', 'Macau', ''),
    (440, 'National Research University Higher School of Economics', 'Russia', 'HSE, Moscow'),
    (440, 'Universität Konstanz', 'Germany', ''),
    (440, 'University of California, Riverside', 'United States', ''),
    (446, 'Vilnius University', 'Lithuania', ''),
    (447, 'Belarusian State University', 'Belarus', ''),
    (448, 'Universität Bayreuth', 'Germany', ''),
    (449, 'Iowa State University', 'United States', ''),
    (450, 'Kazan Federal University', 'Russia', ''),
    (450, 'Universidade Estadual Paulista "Júlio de Mesquita Filho"', 'Brazil', 'UNESP'),
    (452, 'Johannes Gutenberg Universität Mainz', 'Germany', ''),
    (452, 'Shenzhen University', 'China', ''),
    (452, 'Stony Brook University', 'United States', ''),
    (452, 'University of Cyprus', 'Cyprus', ''),
    (456, 'Amirkabir University of Technology', 'Iran', ''),
    (456, 'University of Essex', 'United Kingdom', ''),
    (458, 'Colorado State University', 'United States', ''),
    (458, 'Universidad Nacional de La Plata', 'Argentina', ''),
    (458, 'University of California, Santa Cruz', 'United States', ''),
    (461, 'Jordan University of Science & Technology', 'Jordan', ''),
    (461, 'Novosibirsk State University', 'Russia', ''),
    (461, 'Royal Holloway University of London', 'United Kingdom', ''),
    (461, 'Università Vita-Salute San Raffaele', 'Italy', ''),
    (465, 'Anna University', 'India', ''),
    (465, 'Concordia University', 'Canada', ''),
    (465, 'Shanghai University', 'China', ''),
    (465, 'University of Kansas', 'United States', ''),
    (469, 'Ben Gurion University of The Negev', 'Israel', ''),
    (469, 'Laval University', 'Canada', ''),
    (469, 'Tashkent Institute of Irrigation and Agricultural Mechanization Engineers - National Research University', 'Uzbekistan', 'TIIAME-NRU'),
    (469, 'Universidad de Sevilla', 'Spain', ''),
    (473, 'Jilin University', 'China', ''),
    (473, 'Johannes Kepler University Linz', 'Austria', ''),
    (473, 'Pusan National University', 'South Korea', ''),
    (473, 'Università della Svizzera Italiana', 'Switzerland', ''),
    (477, 'Moscow Institute of Physics and Technology State University', 'Russia', ''),
    (477, 'Universität Potsdam', 'Germany', ''),
    (479, 'Chung-Ang University', 'South Korea', ''),
    (480, 'Hiroshima University', 'Japan', ''),
    (480, 'University of Science and Technology Beijing', 'China', ''),
    (482, 'Dalian University of Technology', 'China', ''),
    (482, 'Duy Tan University', 'Vietnam', ''),
    (482, 'Kobe University', 'Japan', ''),
    (485, 'Aristotle University of Thessaloniki', 'Greece', ''),
    (485, 'University of Trento', 'Italy', ''),
    (487, 'Edith Cowan University', 'Australia', ''),
    (487, 'Technische Universität Bergakademie Freiberg', 'Germany', ''),
    (487, 'Warsaw University of Technology', 'Poland', ''),
    (490, 'Universidad de Santiago de Chile - USACH', 'Chile', ''),
    (491, 'Central South University', 'China', ''),
    (491, 'Imam Abdulrahman Bin Faisal University', 'Saudi Arabia', ''),
    (491, 'Universiti Utara Malaysia', 'Malaysia', 'UUM'),
    (494, 'Université de Bordeaux', 'France', ''),
    (494, 'University of Canberra', 'Australia', ''),
    (496, 'Iran University of Science and Technology', 'Iran', ''),
    (496, 'Justus-Liebig-Universität Gießen', 'Germany', ''),
    (498, 'University of Jyväskylä', 'Finland', ''),
    (499, 'Central Queensland University Australia', 'Australia', 'CQUniversity'),
    (499, 'Northwestern Polytechnical University', 'China', ''),
    (499, 'Tomsk State University', 'Russia', ''),
    (499, 'Universidad de Costa Rica', 'Costa Rica', ''),
]

QS_EDITION = "2026"

CONTINENTS = {
    '亚洲 / Asia': ['Singapore', 'Hong Kong', 'China', 'Japan', 'South Korea', 'Malaysia', 'Taiwan', 'Saudi Arabia', 'Qatar', 'India', 'Kazakhstan', 'United Arab Emirates', 'Indonesia', 'Thailand', 'Israel', 'Lebanon', 'Turkey', 'Macau', 'Iran', 'Jordan', 'Oman', 'Pakistan', 'Philippines', 'Brunei', 'Cyprus', 'Uzbekistan', 'Vietnam'],
    '欧洲 / Europe': ['United Kingdom', 'Switzerland', 'Germany', 'France', 'Netherlands', 'Belgium', 'Sweden', 'Ireland', 'Italy', 'Denmark', 'Russia', 'Finland', 'Norway', 'Austria', 'Spain', 'Portugal', 'Czechia', 'Poland', 'Greece', 'Estonia', 'Luxembourg', 'Lithuania', 'Belarus'],
    '美洲 / Americas': ['United States', 'Canada', 'Argentina', 'Brazil', 'Chile', 'Mexico', 'Colombia', 'Peru', 'Costa Rica'],
    '大洋洲 / Oceania': ['Australia', 'New Zealand'],
    '非洲 / Africa': ['South Africa', 'Egypt'],
    "其他 / Other": [],
}


COUNTRY_FLAG = {
    'Argentina': '🇦🇷',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Belarus': '🇧🇾',
    'Belgium': '🇧🇪',
    'Brazil': '🇧🇷',
    'Brunei': '🇧🇳',
    'Canada': '🇨🇦',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'Colombia': '🇨🇴',
    'Costa Rica': '🇨🇷',
    'Cyprus': '🇨🇾',
    'Czechia': '🇨🇿',
    'Denmark': '🇩🇰',
    'Egypt': '🇪🇬',
    'Estonia': '🇪🇪',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'Germany': '🇩🇪',
    'Greece': '🇬🇷',
    'Hong Kong': '🇭🇰',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Ireland': '🇮🇪',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Japan': '🇯🇵',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Lebanon': '🇱🇧',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Macau': '🇲🇴',
    'Malaysia': '🇲🇾',
    'Mexico': '🇲🇽',
    'Netherlands': '🇳🇱',
    'New Zealand': '🇳🇿',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Pakistan': '🇵🇰',
    'Peru': '🇵🇪',
    'Philippines': '🇵🇭',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Qatar': '🇶🇦',
    'Russia': '🇷🇺',
    'Saudi Arabia': '🇸🇦',
    'Singapore': '🇸🇬',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'Spain': '🇪🇸',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Taiwan': '🇹🇼',
    'Thailand': '🇹🇭',
    'Turkey': '🇹🇷',
    'United Arab Emirates': '🇦🇪',
    'United Kingdom': '🇬🇧',
    'United States': '🇺🇸',
    'Uzbekistan': '🇺🇿',
    'Vietnam': '🇻🇳',
}
