"""Auto-generated from QS World University Rankings 2027 (top 500).
Single source of truth for the university dropdown, QS-rank lookup, and
school-name normalization on import. Do not edit by hand - regenerate.
"""

# (rank, official_name, country, alias)
QS_TOP500 = [
    (1, 'Massachusetts Institute of Technology', 'United States', 'MIT'),
    (2, 'Imperial College London', 'United Kingdom', ''),
    (2, 'Stanford University', 'United States', ''),
    (4, 'University of Oxford', 'United Kingdom', ''),
    (5, 'Harvard University', 'United States', ''),
    (6, 'University of Cambridge', 'United Kingdom', ''),
    (7, 'California Institute of Technology', 'United States', 'Caltech'),
    (8, 'ETH Zurich', 'Switzerland', ''),
    (8, 'UCL', 'United Kingdom', ''),
    (10, 'National University of Singapore', 'Singapore', 'NUS'),
    (11, 'The University of Hong Kong', 'Hong Kong', ''),
    (12, 'Nanyang Technological University, Singapore', 'Singapore', ''),
    (13, 'Peking University', 'China', ''),
    (14, 'Tsinghua University', 'China', ''),
    (15, 'University of Pennsylvania', 'United States', ''),
    (16, 'Cornell University', 'United States', ''),
    (16, 'Yale University', 'United States', ''),
    (18, 'The Chinese University of Hong Kong', 'Hong Kong', ''),
    (19, 'The University of New South Wales', 'Australia', ''),
    (20, 'Johns Hopkins University', 'United States', ''),
    (20, 'University of California, Berkeley', 'United States', 'UCB'),
    (22, 'EPFL – École polytechnique fédérale de Lausanne', 'Switzerland', ''),
    (22, 'The University of Melbourne', 'Australia', ''),
    (24, 'University of Chicago', 'United States', ''),
    (25, 'Technical University of Munich', 'Germany', ''),
    (26, 'Fudan University', 'China', ''),
    (27, 'Princeton University', 'United States', ''),
    (28, 'The University of Sydney', 'Australia', ''),
    (29, 'Australian National University', 'Australia', ''),
    (30, 'McGill University', 'Canada', ''),
    (31, 'Monash University', 'Australia', ''),
    (32, 'University of Toronto', 'Canada', ''),
    (33, 'The Hong Kong University of Science and Technology', 'Hong Kong', ''),
    (34, 'Université PSL', 'France', ''),
    (35, 'The University of Edinburgh', 'United Kingdom', ''),
    (36, 'Shanghai Jiao Tong University', 'China', ''),
    (37, "King's College London", 'United Kingdom', 'KCL'),
    (38, 'Seoul National University', 'South Korea', ''),
    (39, 'The University of Tokyo', 'Japan', ''),
    (40, 'The University of Manchester', 'United Kingdom', ''),
    (40, 'The University of Queensland', 'Australia', ''),
    (42, 'Yonsei University', 'South Korea', ''),
    (43, 'Columbia University', 'United States', ''),
    (43, 'Institut Polytechnique de Paris', 'France', ''),
    (45, 'Northwestern University', 'United States', ''),
    (45, 'University of British Columbia', 'Canada', ''),
    (47, 'Zhejiang University', 'China', ''),
    (48, 'Delft University of Technology', 'Netherlands', ''),
    (49, 'University of California, Los Angeles', 'United States', 'UCLA'),
    (50, 'The Hong Kong Polytechnic University', 'Hong Kong', ''),
    (51, 'University of Michigan-Ann Arbor', 'United States', ''),
    (52, 'City University of Hong Kong', 'Hong Kong', ''),
    (52, 'Korea University', 'South Korea', ''),
    (54, 'National Taiwan University', 'Taiwan', 'NTU'),
    (55, 'Carnegie Mellon University', 'United States', ''),
    (56, 'Universiti Malaya', 'Malaysia', 'UM'),
    (57, 'University of Bristol', 'United Kingdom', ''),
    (58, 'New York University', 'United States', 'NYU'),
    (59, 'KU Leuven', 'Belgium', ''),
    (60, 'University of Amsterdam', 'Netherlands', ''),
    (61, 'Ludwig-Maximilians-Universität München', 'Germany', ''),
    (62, 'The London School of Economics and Political Science', 'United Kingdom', ''),
    (63, 'KFUPM', 'Saudi Arabia', ''),
    (64, 'Kyoto University', 'Japan', ''),
    (65, 'KAIST', 'South Korea', ''),
    (66, 'Brown University', 'United States', ''),
    (67, 'The University of Auckland', 'New Zealand', ''),
    (68, 'The University of Warwick', 'United Kingdom', ''),
    (68, 'University of Birmingham', 'United Kingdom', ''),
    (70, 'Duke University', 'United States', ''),
    (71, 'Lund University', 'Sweden', ''),
    (72, 'University of Texas at Austin', 'United States', ''),
    (73, 'Sorbonne University', 'France', ''),
    (74, 'University of Illinois Urbana-Champaign', 'United States', ''),
    (75, 'Trinity College Dublin, The University of Dublin', 'Ireland', ''),
    (76, 'Université Paris-Saclay', 'France', ''),
    (77, 'The University of Western Australia', 'Australia', ''),
    (77, 'University of Leeds', 'United Kingdom', ''),
    (79, 'Adelaide University', 'Australia', ''),
    (80, 'University of Glasgow', 'United Kingdom', ''),
    (81, 'University of California, San Diego', 'United States', 'UCSD'),
    (82, 'KTH Royal Institute of Technology', 'Sweden', ''),
    (82, 'The University of Sheffield', 'United Kingdom', ''),
    (84, 'Universidad de Buenos Aires', 'Argentina', ''),
    (85, 'Durham University', 'United Kingdom', ''),
    (86, 'Universität Heidelberg', 'Germany', ''),
    (87, 'Politecnico di Milano', 'Italy', ''),
    (87, 'University of Technology Sydney', 'Australia', ''),
    (87, 'Uppsala University', 'Sweden', ''),
    (90, 'Nanjing University', 'China', ''),
    (90, 'University of Copenhagen', 'Denmark', ''),
    (92, 'Pennsylvania State University', 'United States', ''),
    (92, 'University of Washington', 'United States', ''),
    (94, 'Boston University', 'United States', ''),
    (95, 'The University of Osaka', 'Japan', ''),
    (96, 'University of Alberta', 'Canada', ''),
    (97, 'Institute of Science Tokyo', 'Japan', ''),
    (97, 'University of Nottingham', 'United Kingdom', ''),
    (98, 'Freie Universitaet Berlin', 'Germany', ''),
    (98, 'University of Zurich', 'Switzerland', 'UZH'),
    (100, 'Purdue University', 'United States', ''),
    (100, 'University College Dublin', 'Ireland', ''),
    (102, 'Tohoku University', 'Japan', ''),
    (103, 'Queen Mary University of London', 'United Kingdom', 'QMUL'),
    (104, 'RWTH Aachen University', 'Germany', ''),
    (105, 'Technical University of Denmark', 'Denmark', ''),
    (106, 'Pohang University of Science And Technology', 'South Korea', 'POSTECH'),
    (107, 'King Saud University', 'Saudi Arabia', ''),
    (108, 'Sungkyunkwan University', 'South Korea', ''),
    (109, 'Qatar University', 'Qatar', ''),
    (110, 'KIT, Karlsruhe Institute of Technology', 'Germany', ''),
    (111, 'Sapienza University of Rome', 'Italy', ''),
    (111, 'University of Southampton', 'United Kingdom', ''),
    (113, 'University of Waterloo', 'Canada', ''),
    (113, 'Utrecht University', 'Netherlands', ''),
    (115, 'Lomonosov Moscow State University', 'Russia', ''),
    (115, 'University of St Andrews', 'United Kingdom', ''),
    (118, 'Indian Institute of Technology Delhi', 'India', 'IITD'),
    (119, 'Leiden University', 'Netherlands', ''),
    (119, 'Pontificia Universidad Católica de Chile', 'Chile', ''),
    (119, 'RMIT University', 'Australia', ''),
    (122, 'Rice University', 'United States', ''),
    (123, 'Alma Mater Studiorum - Università di Bologna', 'Italy', ''),
    (123, 'University of Helsinki', 'Finland', ''),
    (125, 'University of Bath', 'United Kingdom', ''),
    (126, 'Aalto University', 'Finland', ''),
    (126, 'Macquarie University', 'Australia', ''),
    (128, 'Aarhus University', 'Denmark', ''),
    (128, 'Universiti Sains Malaysia', 'Malaysia', 'USM'),
    (130, 'Universiti Kebangsaan Malaysia', 'Malaysia', 'UKM'),
    (131, 'University of Oslo', 'Norway', ''),
    (131, 'University of Wisconsin-Madison', 'United States', ''),
    (133, 'Universidade de São Paulo', 'Brazil', 'USP'),
    (134, 'Indian Institute of Technology Bombay', 'India', 'IITB'),
    (134, 'University of Science and Technology of China', 'China', ''),
    (136, 'University of Exeter', 'United Kingdom', ''),
    (137, 'University of California, Davis', 'United States', ''),
    (138, 'Universiti Putra Malaysia', 'Malaysia', 'UPM'),
    (139, 'University of Liverpool', 'United Kingdom', ''),
    (140, 'Humboldt-Universität zu Berlin', 'Germany', ''),
    (140, 'University of Vienna', 'Austria', ''),
    (142, 'Georgia Institute of Technology', 'United States', ''),
    (142, 'National Tsing Hua University - NTHU', 'Taiwan', ''),
    (142, 'Western University', 'Canada', ''),
    (145, 'Universidad Nacional Autónoma de México', 'Mexico', 'UNAM'),
    (146, 'Tongji University', 'China', ''),
    (147, 'Khalifa University', 'United Arab Emirates', ''),
    (148, 'Erasmus University Rotterdam', 'Netherlands', ''),
    (149, 'Newcastle University', 'United Kingdom', ''),
    (150, 'Ghent University', 'Belgium', ''),
    (150, 'University of Basel', 'Switzerland', ''),
    (152, 'Eindhoven University of Technology', 'Netherlands', ''),
    (153, 'University of Southern California', 'United States', ''),
    (154, 'Wageningen University & Research', 'Netherlands', ''),
    (155, 'Hanyang University', 'South Korea', ''),
    (156, 'Nagoya University', 'Japan', ''),
    (157, 'University of Groningen', 'Netherlands', ''),
    (158, 'Technische Universität Berlin', 'Germany', ''),
    (158, 'Universiti Teknologi Malaysia', 'Malaysia', 'UTM'),
    (158, 'University of North Carolina at Chapel Hill', 'United States', ''),
    (158, 'University of York', 'United Kingdom', ''),
    (162, 'Université de Montréal', 'Canada', ''),
    (162, 'Washington University in St. Louis', 'United States', ''),
    (164, 'Lancaster University', 'United Kingdom', ''),
    (165, 'Universitat de Barcelona', 'Spain', ''),
    (165, 'Wuhan University', 'China', ''),
    (167, 'Stockholm University', 'Sweden', ''),
    (168, 'University of Geneva', 'Switzerland', ''),
    (169, 'Texas A&M University', 'United States', ''),
    (170, 'Indian Institute of Technology Madras', 'India', 'IITM'),
    (171, 'Kyushu University', 'Japan', ''),
    (172, 'Arizona State University', 'United States', ''),
    (173, 'University of California, Santa Barbara', 'United States', 'UCSB'),
    (174, 'Chalmers University of Technology', 'Sweden', ''),
    (174, 'McMaster University', 'Canada', ''),
    (174, "Queen's University Belfast", 'United Kingdom', ''),
    (177, 'Al-Farabi Kazakh National University', 'Kazakhstan', ''),
    (177, 'National Yang Ming Chiao Tung University', 'Taiwan', ''),
    (179, 'Cardiff University', 'United Kingdom', ''),
    (179, 'Hokkaido University', 'Japan', ''),
    (179, "Queen's University at Kingston", 'Canada', ''),
    (182, 'Michigan State University', 'United States', ''),
    (183, 'Emory University', 'United States', ''),
    (184, 'University of Cape Town', 'South Africa', ''),
    (185, 'Technische Universität Dresden', 'Germany', ''),
    (185, 'Universidad de Chile', 'Chile', ''),
    (185, 'Vrije Universiteit Amsterdam', 'Netherlands', ''),
    (188, 'Tecnológico de Monterrey', 'Mexico', 'ITESM'),
    (189, 'Curtin University', 'Australia', ''),
    (190, 'Harbin Institute of Technology', 'China', ''),
    (191, 'National Cheng Kung University', 'Taiwan', 'NCKU'),
    (191, 'Technische Universität Wien', 'Austria', ''),
    (191, 'Universitas Indonesia', 'Indonesia', ''),
    (191, 'University of Bern', 'Switzerland', ''),
    (195, 'University of Wollongong', 'Australia', ''),
    (196, 'Université catholique de Louvain', 'Belgium', ''),
    (196, 'University of Reading', 'United Kingdom', ''),
    (198, 'University of Otago', 'New Zealand', ''),
    (199, 'Complutense University of Madrid', 'Spain', ''),
    (200, 'King Abdulaziz University', 'Saudi Arabia', ''),
    (201, 'The Ohio State University', 'United States', ''),
    (201, 'Waseda University', 'Japan', ''),
    (203, 'Loughborough University', 'United Kingdom', ''),
    (204, 'Università\xa0di Padova', 'Italy', ''),
    (205, 'Indian Institute of Technology Kharagpur', 'India', 'IITKGP'),
    (206, 'Gadjah Mada University', 'Indonesia', ''),
    (206, 'Politecnico di Torino', 'Italy', ''),
    (208, 'Tel Aviv University', 'Israel', ''),
    (209, 'Rheinische Friedrich-Wilhelms-Universität Bonn', 'Germany', ''),
    (209, 'Universität Hamburg', 'Germany', ''),
    (211, 'Universitat Autònoma de Barcelona', 'Spain', ''),
    (212, 'Chulalongkorn University', 'Thailand', ''),
    (213, 'Hamad Bin Khalifa University', 'Qatar', ''),
    (213, 'Keio University', 'Japan', ''),
    (215, 'Massey University', 'New Zealand', ''),
    (216, 'Hong Kong Baptist University', 'Hong Kong', ''),
    (217, 'United Arab Emirates University', 'United Arab Emirates', ''),
    (218, 'Friedrich-Alexander-Universität Erlangen-Nürnberg', 'Germany', ''),
    (218, 'The Hebrew University of Jerusalem', 'Israel', ''),
    (220, 'University College Cork', 'Ireland', ''),
    (221, 'Indian Institute of Science (IISc) Bangalore', 'India', ''),
    (221, 'Indian Institute of Technology Kanpur', 'India', 'IITK'),
    (223, 'American University of Beirut', 'Lebanon', 'AUB'),
    (223, 'University of Twente', 'Netherlands', ''),
    (225, 'University of Gothenburg', 'Sweden', ''),
    (226, 'Universidad Autónoma de Madrid', 'Spain', ''),
    (227, 'Deakin University', 'Australia', ''),
    (228, 'University of Florida', 'United States', ''),
    (228, 'University of Ottawa', 'Canada', ''),
    (230, 'Eberhard Karls Universität Tübingen', 'Germany', ''),
    (230, 'Griffith University', 'Australia', ''),
    (230, 'University of Strathclyde', 'United Kingdom', ''),
    (233, 'Universidad de los Andes', 'Colombia', ''),
    (233, 'University of Lausanne', 'Switzerland', ''),
    (235, 'École Normale Supérieure de Lyon', 'France', ''),
    (235, 'Tianjin University', 'China', ''),
    (237, 'Beijing Normal University', 'China', ''),
    (237, 'University of Lisbon', 'Portugal', ''),
    (239, 'Central European University', 'Austria', ''),
    (240, 'Queensland University of Technology', 'Australia', ''),
    (241, 'La Trobe University', 'Australia', ''),
    (241, 'Victoria University of Wellington', 'New Zealand', ''),
    (243, 'Beijing Institute of Technology', 'China', ''),
    (244, 'The University of Newcastle, Australia', 'Australia', ''),
    (245, 'Albert-Ludwigs-Universitaet Freiburg', 'Germany', ''),
    (246, 'Université Paris 1 Panthéon-Sorbonne', 'France', ''),
    (246, 'University of Surrey', 'United Kingdom', ''),
    (248, 'Universite libre de Bruxelles', 'Belgium', ''),
    (249, 'University of Calgary', 'Canada', ''),
    (250, 'Technical University of Darmstadt', 'Germany', ''),
    (251, 'University of Rochester', 'United States', ''),
    (252, 'University of California, Irvine', 'United States', ''),
    (252, 'University of Maryland, College Park', 'United States', ''),
    (254, 'Maastricht University', 'Netherlands', ''),
    (255, 'University of Minnesota', 'United States', 'System'),
    (255, 'University of Porto', 'Portugal', ''),
    (257, 'University of Canterbury | Te Whare Wānanga o Waitaha', 'New Zealand', ''),
    (258, 'American University of Sharjah', 'United Arab Emirates', 'AUS'),
    (258, 'Sun Yat-sen University', 'China', ''),
    (260, 'University of Massachusetts Amherst', 'United States', ''),
    (261, 'Universiti Teknologi PETRONAS', 'Malaysia', ''),
    (261, 'University of Göttingen', 'Germany', ''),
    (263, 'Universitat Pompeu Fabra', 'Spain', ''),
    (264, 'Norwegian University of Science And Technology', 'Norway', ''),
    (265, 'Vanderbilt University', 'United States', ''),
    (266, 'Singapore University of Technology and Design', 'Singapore', ''),
    (267, 'University of Macau', 'Macau', ''),
    (268, 'University of Virginia', 'United States', ''),
    (269, 'University of Cologne', 'Germany', ''),
    (270, 'Dartmouth College', 'United States', ''),
    (270, 'University of Milan', 'Italy', ''),
    (272, "Taylor's University", 'Malaysia', 'Malaysia'),
    (273, 'Charles University', 'Czechia', ''),
    (273, 'University of Sussex', 'United Kingdom', ''),
    (275, 'University of Galway', 'Ireland', ''),
    (276, 'Universitas Airlangga', 'Indonesia', ''),
    (277, 'Universidade Estadual de Campinas', 'Brazil', 'Unicamp'),
    (277, 'University of Antwerp', 'Belgium', ''),
    (279, 'Istanbul Technical University', 'Turkey', ''),
    (279, 'University of Navarra', 'Spain', ''),
    (279, 'University of Pittsburgh', 'United States', ''),
    (282, 'UCSI University', 'Malaysia', ''),
    (283, 'Radboud University', 'Netherlands', ''),
    (283, 'University of Bergen', 'Norway', ''),
    (283, 'University of Sharjah', 'United Arab Emirates', ''),
    (283, 'University of Southern Denmark', 'Denmark', ''),
    (287, 'Institut Teknologi Bandung', 'Indonesia', ''),
    (288, 'University of Aberdeen', 'United Kingdom', ''),
    (289, 'Georgetown University', 'United States', ''),
    (289, 'University of Warsaw', 'Poland', ''),
    (291, 'Swinburne University of Technology', 'Australia', ''),
    (292, 'University of Johannesburg', 'South Africa', ''),
    (293, 'Universidad Nacional de Colombia', 'Colombia', ''),
    (293, 'University of Waikato', 'New Zealand', ''),
    (295, 'Vrije Universiteit Brussel', 'Belgium', 'VUB'),
    (296, 'Stellenbosch University', 'South Africa', ''),
    (296, 'Xi’an Jiaotong University', 'China', ''),
    (298, 'Dalhousie University', 'Canada', ''),
    (299, 'Ulsan National Institute of Science and Technology', 'South Korea', ''),
    (300, 'Sichuan University', 'China', ''),
    (300, 'University of Notre Dame', 'United States', ''),
    (302, 'University of Witwatersrand', 'South Africa', ''),
    (303, 'Université Paris Cité', 'France', ''),
    (303, 'Xiamen University', 'China', ''),
    (305, 'Middle East Technical University', 'Turkey', ''),
    (306, 'Sultan Qaboos University', 'Oman', ''),
    (307, 'Huazhong University of Science and Technology', 'China', ''),
    (308, 'Linköping University', 'Sweden', ''),
    (309, 'Kyung Hee University', 'South Korea', ''),
    (309, 'Shandong University', 'China', ''),
    (311, 'University of Tasmania', 'Australia', ''),
    (312, 'Simon Fraser University', 'Canada', ''),
    (313, 'The University of Arizona', 'United States', ''),
    (314, 'Rutgers University–New Brunswick', 'United States', ''),
    (314, 'Universidad Carlos III de Madrid', 'Spain', ''),
    (314, 'University of Leicester', 'United Kingdom', ''),
    (317, 'Southern University of Science and Technology', 'China', 'SUSTech'),
    (318, 'Bauman Moscow State Technical University', 'Russia', ''),
    (318, 'Universität Stuttgart', 'Germany', ''),
    (320, 'North Carolina State University', 'United States', ''),
    (320, 'University of Colorado Boulder', 'United States', ''),
    (322, 'Swansea University', 'United Kingdom', ''),
    (322, 'University of Delhi', 'India', ''),
    (322, 'York University', 'Canada', ''),
    (325, 'Heriot-Watt University', 'United Kingdom', ''),
    (326, 'Case Western Reserve University', 'United States', ''),
    (326, 'University of Jordan', 'Jordan', ''),
    (326, 'University of Pretoria', 'South Africa', ''),
    (329, 'Aalborg University', 'Denmark', ''),
    (329, 'Jagiellonian University', 'Poland', ''),
    (329, 'Koç University', 'Turkey', ''),
    (329, 'Nankai University', 'China', ''),
    (333, 'Universität Innsbruck', 'Austria', ''),
    (334, 'Technion - Israel Institute of Technology', 'Israel', ''),
    (335, 'Indian Institute of Technology Roorkee', 'India', 'IITR'),
    (335, 'Southeast University', 'China', ''),
    (337, 'Universidade Nova de Lisboa', 'Portugal', ''),
    (338, 'L.N. Gumilyov Eurasian National University', 'Kazakhstan', ''),
    (338, 'Tufts University', 'United States', ''),
    (338, 'University of Miami', 'United States', ''),
    (341, 'University of Pisa', 'Italy', ''),
    (342, 'South China University of Technology', 'China', ''),
    (342, 'University of Coimbra', 'Portugal', ''),
    (342, 'University of Rome "Tor Vergata"', 'Italy', ''),
    (345, 'Boğaziçi University', 'Turkey', ''),
    (345, 'Mahidol University', 'Thailand', ''),
    (345, 'Universiti Brunei Darussalam', 'Brunei', 'UBD'),
    (348, 'Abu Dhabi University', 'United Arab Emirates', ''),
    (349, 'Beihang University', 'China', 'former BUAA'),
    (349, 'Indian Institute of Technology Guwahati', 'India', 'IITG'),
    (351, 'Satbayev University', 'Kazakhstan', ''),
    (351, 'University of Tsukuba', 'Japan', ''),
    (353, 'Brunel University of London', 'United Kingdom', ''),
    (354, 'Birkbeck, University of London', 'United Kingdom', ''),
    (354, 'Sciences Po', 'France', ''),
    (354, 'Sunway University', 'Malaysia', ''),
    (357, 'Pontificia Universidad Catolica del Peru', 'Peru', ''),
    (357, 'Sabanci University', 'Turkey', ''),
    (359, 'RUDN University', 'Russia', ''),
    (360, 'Indiana University Bloomington', 'United States', ''),
    (360, 'University of Chinese Academy of Sciences', 'China', 'UCAS'),
    (360, 'University of Oulu', 'Finland', ''),
    (361, 'City St George’s, University of London', 'United Kingdom', ''),
    (363, 'Cairo University', 'Egypt', ''),
    (364, 'Universidad Politécnica de Madrid', 'Spain', ''),
    (364, 'Université de Liège', 'Belgium', ''),
    (366, 'Virginia Polytechnic Institute and State University', 'United States', ''),
    (367, 'Universidade Federal do Rio de Janeiro', 'Brazil', ''),
    (367, 'University of Tartu', 'Estonia', ''),
    (367, 'University of Tehran', 'Iran', ''),
    (370, 'University of Illinois Chicago', 'United States', 'UIC'),
    (370, 'University of Münster', 'Germany', ''),
    (370, 'University of Victoria', 'Canada', ''),
    (370, 'Western Sydney University', 'Australia', ''),
    (374, 'Flinders University', 'Australia', ''),
    (376, 'Goethe-University Frankfurt am Main', 'Germany', ''),
    (376, 'University of Luxembourg', 'Luxembourg', ''),
    (378, 'National Technical University of Athens', 'Greece', ''),
    (379, 'Gwangju Institute of Science and Technology', 'South Korea', 'GIST'),
    (379, 'National Taiwan University of Science and Technology', 'Taiwan', 'Taiwan Tech'),
    (381, 'George Washington University', 'United States', ''),
    (381, 'Quaid-i-Azam University', 'Pakistan', ''),
    (381, 'University of East Anglia', 'United Kingdom', 'UEA'),
    (384, 'National University of Sciences & Technology (NUST) Islamabad', 'Pakistan', ''),
    (385, 'Daegu Gyeongbuk Institute of Science and Technology', 'South Korea', 'DGIST'),
    (385, 'Northeastern University', 'United States', ''),
    (387, 'Université Grenoble Alpes', 'France', ''),
    (388, 'Università\xa0Cattolica del Sacro Cuore', 'Italy', ''),
    (388, 'University of Limerick', 'Ireland', ''),
    (390, 'LUT University', 'Finland', ''),
    (390, 'Saint Petersburg State University', 'Russia', ''),
    (390, 'Sharif University of Technology', 'Iran', ''),
    (390, 'The American University in Cairo', 'Egypt', ''),
    (394, 'East China Normal University', 'China', ''),
    (395, 'Pontificia Universidad Javeriana', 'Colombia', ''),
    (395, 'Università degli Studi di Pavia', 'Italy', ''),
    (397, 'Ajman University', 'United Arab Emirates', ''),
    (398, 'Macau University of Science and Technology', 'Macau', ''),
    (398, 'Sejong University', 'South Korea', ''),
    (398, 'University of California, Riverside', 'United States', ''),
    (398, 'University of Turku', 'Finland', ''),
    (401, 'University of Naples - Federico II', 'Italy', ''),
    (402, 'National and Kapodistrian University of Athens', 'Greece', ''),
    (402, 'Ruhr-Universität Bochum', 'Germany', ''),
    (402, 'University of the Philippines', 'Philippines', ''),
    (405, 'University of Turin', 'Italy', ''),
    (406, 'INTI International University', 'Malaysia', ''),
    (406, 'The Education University of Hong Kong', 'Hong Kong', ''),
    (408, 'Dublin City University', 'Ireland', ''),
    (409, 'Graz University of Technology', 'Austria', ''),
    (409, 'University of Florence', 'Italy', ''),
    (411, 'Oxford Brookes University', 'United Kingdom', ''),
    (411, 'Singapore Management University', 'Singapore', ''),
    (411, 'University of Saskatchewan', 'Canada', ''),
    (411, 'University of Southern Queensland', 'Australia', ''),
    (415, 'University of Kent', 'United Kingdom', ''),
    (416, 'Aston University', 'United Kingdom', ''),
    (416, 'Shenzhen University', 'China', ''),
    (416, 'University at Buffalo SUNY', 'United States', ''),
    (419, 'IPB University', 'Indonesia', ''),
    (419, 'Lincoln University', 'New Zealand', ''),
    (421, 'Prince Mohammad Bin Fahd university', 'Saudi Arabia', ''),
    (422, 'Murdoch University', 'Australia', ''),
    (423, 'HSE University', 'Russia', ''),
    (423, 'National Taiwan Normal University', 'Taiwan', ''),
    (425, 'Northwestern Polytechnical University', 'China', ''),
    (425, 'Universität Konstanz', 'Germany', ''),
    (425, 'Universität Mannheim', 'Germany', ''),
    (425, 'University of Aveiro', 'Portugal', ''),
    (429, 'Tilburg University', 'Netherlands', ''),
    (430, 'Julius-Maximilians-Universität Würzburg', 'Germany', ''),
    (431, 'Auckland University of Technology', 'New Zealand', ''),
    (432, 'Chung-Ang University', 'South Korea', ''),
    (432, 'Czech Technical University in Prague', 'Czechia', ''),
    (434, 'Universitat Politècnica de Catalunya · BarcelonaTech', 'Spain', ''),
    (434, 'Universitat Politecnica de Valencia', 'Spain', ''),
    (436, 'Central Queensland University', 'Australia', ''),
    (436, 'Tampere University', 'Finland', ''),
    (438, 'Essex, University of', 'United Kingdom', ''),
    (438, 'James Cook University', 'Australia', ''),
    (438, 'National Sun Yat-sen University', 'Taiwan', ''),
    (438, 'Umea University', 'Sweden', ''),
    (438, 'University of Trento', 'Italy', ''),
    (443, 'Aix-Marseille University', 'France', ''),
    (443, 'Shanghai University', 'China', ''),
    (443, 'University of Science and Technology Beijing', 'China', ''),
    (446, 'IE University', 'Spain', ''),
    (447, 'University of Dundee', 'United Kingdom', ''),
    (447, 'University of Granada', 'Spain', ''),
    (449, 'Jordan University of Science & Technology', 'Jordan', ''),
    (449, 'Pusan National University', 'South Korea', ''),
    (449, 'Universitat de Valencia', 'Spain', ''),
    (452, 'Central South University', 'China', ''),
    (452, 'Shoolini University of Biotechnology and Management Sciences', 'India', ''),
    (454, 'Bilkent University', 'Turkey', ''),
    (454, 'Masaryk University', 'Czechia', ''),
    (456, 'Université de Strasbourg', 'France', ''),
    (456, 'USI - Università della Svizzera italiana', 'Switzerland', ''),
    (458, 'Johannes Kepler University Linz', 'Austria', ''),
    (458, 'SOAS University of London', 'United Kingdom', ''),
    (458, 'Tashkent Institute of Irrigation and Agricultural Mechanization Engineers - National Research University', 'Uzbekistan', 'TIIAME-NRU'),
    (458, 'University of California, Santa Cruz', 'United States', ''),
    (458, 'University of Connecticut', 'United States', ''),
    (463, 'Dalian University of Technology', 'China', ''),
    (463, 'Universidad de Costa Rica', 'Costa Rica', ''),
    (465, 'Chongqing University', 'China', ''),
    (465, 'Università Vita-Salute San Raffaele', 'Italy', ''),
    (465, 'Vilnius University', 'Lithuania', ''),
    (468, 'Kazan (Volga region) Federal University', 'Russia', ''),
    (468, 'Stony Brook University, State University of New York', 'United States', ''),
    (470, 'Anna University', 'India', ''),
    (470, 'Leibniz University Hannover', 'Germany', ''),
    (472, 'University of Bayreuth', 'Germany', ''),
    (473, 'Université de Montpellier', 'France', ''),
    (474, 'Imam Abdulrahman Bin Faisal University', 'Saudi Arabia', ''),
    (474, 'Universidad Nacional de La Plata', 'Argentina', ''),
    (474, 'Universitat Ramon Llull', 'Spain', ''),
    (477, 'China Agricultural University', 'China', ''),
    (477, 'Hunan University', 'China', ''),
    (477, 'Lebanese American University', 'Lebanon', ''),
    (477, 'University of Canberra', 'Australia', ''),
    (481, 'Hiroshima University', 'Japan', ''),
    (481, 'Kyungpook National University', 'South Korea', ''),
    (483, 'Amirkabir University of Technology', 'Iran', ''),
    (483, 'Jinan University', 'China', ''),
    (485, 'Royal Holloway, University of London', 'United Kingdom', ''),
    (485, 'Universidad de Sevilla', 'Spain', ''),
    (485, 'University of Bordeaux', 'France', ''),
    (488, 'Ewha Womans University', 'South Korea', ''),
    (488, 'Jilin University', 'China', ''),
    (488, 'Novosibirsk State University', 'Russia', ''),
    (488, 'Prince Sultan University', 'Saudi Arabia', ''),
    (488, 'University of Electronic Science and Technology of China', 'China', ''),
    (494, 'National Taipei University of Technology', 'Taiwan', ''),
    (494, 'Sogang University', 'South Korea', ''),
    (496, 'Universitas Padjadjaran', 'Indonesia', ''),
    (497, 'Concordia University', 'Canada', ''),
    (497, 'Institut Teknologi Sepuluh Nopember', 'Indonesia', ''),
    (497, 'University of Bradford', 'United Kingdom', ''),
    (500, 'Johannes Gutenberg Universität Mainz', 'Germany', ''),
    (500, 'Universität Potsdam', 'Germany', ''),
]

QS_EDITION = "2027"

CONTINENTS = {
    '亚洲 / Asia': ['Singapore', 'Hong Kong', 'China', 'Japan', 'South Korea', 'Malaysia', 'Taiwan', 'Saudi Arabia', 'Qatar', 'India', 'Kazakhstan', 'United Arab Emirates', 'Indonesia', 'Thailand', 'Israel', 'Lebanon', 'Turkey', 'Macau', 'Iran', 'Jordan', 'Oman', 'Pakistan', 'Philippines', 'Brunei', 'Cyprus', 'Uzbekistan', 'Vietnam'],
    '欧洲 / Europe': ['United Kingdom', 'Switzerland', 'Germany', 'France', 'Netherlands', 'Belgium', 'Sweden', 'Ireland', 'Italy', 'Denmark', 'Russia', 'Finland', 'Norway', 'Austria', 'Spain', 'Portugal', 'Czechia', 'Poland', 'Greece', 'Estonia', 'Luxembourg', 'Lithuania', 'Belarus'],
    '美洲 / Americas': ['United States', 'Canada', 'Argentina', 'Brazil', 'Chile', 'Mexico', 'Colombia', 'Peru', 'Costa Rica'],
    '大洋洲 / Oceania': ['Australia', 'New Zealand'],
    '非洲 / Africa': ['South Africa', 'Egypt'],
    "其他 / Other": [],
}


COUNTRY_FLAG = {
    'Argentina': '🇦🇷',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Belarus': '🇧🇾',
    'Belgium': '🇧🇪',
    'Brazil': '🇧🇷',
    'Brunei': '🇧🇳',
    'Canada': '🇨🇦',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'Colombia': '🇨🇴',
    'Costa Rica': '🇨🇷',
    'Cyprus': '🇨🇾',
    'Czechia': '🇨🇿',
    'Denmark': '🇩🇰',
    'Egypt': '🇪🇬',
    'Estonia': '🇪🇪',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'Germany': '🇩🇪',
    'Greece': '🇬🇷',
    'Hong Kong': '🇭🇰',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Ireland': '🇮🇪',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Japan': '🇯🇵',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Lebanon': '🇱🇧',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Macau': '🇲🇴',
    'Malaysia': '🇲🇾',
    'Mexico': '🇲🇽',
    'Netherlands': '🇳🇱',
    'New Zealand': '🇳🇿',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Pakistan': '🇵🇰',
    'Peru': '🇵🇪',
    'Philippines': '🇵🇭',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Qatar': '🇶🇦',
    'Russia': '🇷🇺',
    'Saudi Arabia': '🇸🇦',
    'Singapore': '🇸🇬',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'Spain': '🇪🇸',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Taiwan': '🇹🇼',
    'Thailand': '🇹🇭',
    'Turkey': '🇹🇷',
    'United Arab Emirates': '🇦🇪',
    'United Kingdom': '🇬🇧',
    'United States': '🇺🇸',
    'Uzbekistan': '🇺🇿',
    'Vietnam': '🇻🇳',
}
