"""US News & World Report — 2026 Best National Universities (top 100).

Released September 2025. Ranks include ties, so 101 schools span ranks 1–100.
Used to (a) enrich the US school dropdown beyond the QS top-500 and
(b) power the School List ranking page. All schools are in the United States.
"""

USNEWS_EDITION = "2026"

# (rank, official_name, alias)
USNEWS_TOP100 = [
    (1, 'Princeton University', ''),
    (2, 'Massachusetts Institute of Technology', 'MIT'),
    (3, 'Harvard University', ''),
    (4, 'Stanford University', ''),
    (4, 'Yale University', ''),
    (6, 'University of Chicago', 'UChicago'),
    (7, 'Duke University', ''),
    (7, 'Johns Hopkins University', 'JHU'),
    (7, 'Northwestern University', ''),
    (7, 'University of Pennsylvania', 'Penn'),
    (11, 'California Institute of Technology', 'Caltech'),
    (12, 'Cornell University', ''),
    (13, 'Brown University', ''),
    (13, 'Dartmouth College', ''),
    (15, 'Columbia University', ''),
    (15, 'University of California, Berkeley', 'Berkeley'),
    (17, 'Rice University', ''),
    (17, 'University of California, Los Angeles', 'UCLA'),
    (17, 'Vanderbilt University', ''),
    (20, 'Carnegie Mellon University', 'CMU'),
    (20, 'University of Michigan--Ann Arbor', 'Michigan'),
    (20, 'University of Notre Dame', ''),
    (20, 'Washington University in St. Louis', 'WashU'),
    (24, 'Emory University', ''),
    (24, 'Georgetown University', ''),
    (26, 'University of North Carolina--Chapel Hill', 'UNC'),
    (26, 'University of Virginia', 'UVA'),
    (28, 'University of Southern California', 'USC'),
    (29, 'University of California, San Diego', 'UCSD'),
    (30, 'The University of Texas at Austin', 'UT Austin'),
    (30, 'University of Florida', 'UF'),
    (32, 'Georgia Institute of Technology', 'Georgia Tech'),
    (32, 'New York University', 'NYU'),
    (32, 'University of California, Davis', 'UC Davis'),
    (32, 'University of California, Irvine', 'UC Irvine'),
    (36, 'Boston College', 'BC'),
    (36, 'Tufts University', ''),
    (36, 'University of Illinois Urbana-Champaign', 'UIUC'),
    (36, 'University of Wisconsin--Madison', 'UW-Madison'),
    (40, 'The Ohio State University', 'OSU'),
    (40, 'University of California, Santa Barbara', 'UCSB'),
    (42, 'Boston University', 'BU'),
    (42, 'Rutgers University--New Brunswick', 'Rutgers'),
    (42, 'University of Maryland, College Park', 'UMD'),
    (42, 'University of Washington', 'UW'),
    (46, 'Lehigh University', ''),
    (46, 'Northeastern University', ''),
    (46, 'Purdue University--West Lafayette', 'Purdue'),
    (46, 'University of Georgia', 'UGA'),
    (46, 'University of Rochester', ''),
    (51, 'Case Western Reserve University', 'CWRU'),
    (51, 'Florida State University', 'FSU'),
    (51, 'Texas A&M University', 'TAMU'),
    (51, 'Virginia Tech', 'VT'),
    (51, 'Wake Forest University', ''),
    (51, 'William & Mary', 'W&M'),
    (57, 'University of California, Merced', 'UC Merced'),
    (57, 'Villanova University', ''),
    (59, 'George Washington University', 'GW'),
    (59, 'Pennsylvania State University--University Park', 'Penn State'),
    (59, 'Santa Clara University', 'SCU'),
    (59, 'Stony Brook University--SUNY', 'Stony Brook'),
    (59, 'University of Minnesota, Twin Cities', 'UMN'),
    (64, 'Michigan State University', 'MSU'),
    (64, 'North Carolina State University--Raleigh', 'NC State'),
    (64, 'Rensselaer Polytechnic Institute', 'RPI'),
    (64, 'University of Massachusetts--Amherst', 'UMass Amherst'),
    (64, 'University of Miami', ''),
    (69, 'Brandeis University', ''),
    (69, 'Tulane University', ''),
    (69, 'University of Connecticut', 'UConn'),
    (69, 'University of Pittsburgh', 'Pitt'),
    (73, 'Binghamton University--SUNY', 'Binghamton'),
    (73, 'Indiana University--Bloomington', 'IU'),
    (75, 'Clemson University', ''),
    (75, 'Rutgers University--Newark', ''),
    (75, 'Syracuse University', ''),
    (75, 'University at Buffalo--SUNY', 'UB'),
    (75, 'University of California--Riverside', 'UCR'),
    (80, 'Colorado School of Mines', 'Mines'),
    (80, 'Drexel University', ''),
    (80, 'New Jersey Institute of Technology', 'NJIT'),
    (80, 'Stevens Institute of Technology', 'Stevens'),
    (84, 'Pepperdine University', ''),
    (84, 'University of Illinois Chicago', 'UIC'),
    (84, 'Worcester Polytechnic Institute', 'WPI'),
    (84, 'Yeshiva University', 'YU'),
    (88, 'American University', 'AU'),
    (88, 'Baylor University', ''),
    (88, 'Howard University', ''),
    (88, 'Marquette University', ''),
    (88, 'Rochester Institute of Technology', 'RIT'),
    (88, 'Southern Methodist University', 'SMU'),
    (88, 'University of California--Santa Cruz', 'UCSC'),
    (88, 'University of Delaware', 'UD'),
    (88, 'University of South Florida', 'USF'),
    (97, 'Florida International University', 'FIU'),
    (97, 'Fordham University', ''),
    (97, 'Rutgers University--Camden', ''),
    (97, 'Texas Christian University', 'TCU'),
    (97, 'University of Colorado Boulder', 'CU Boulder'),
]
